# Generated by Django 3.2 on 2025-03-29 04:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.IntegerField(default=0)),
                ('gross_profit', models.IntegerField(default=0)),
                ('net_profit', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('number_of_products', models.IntegerField(default=0)),
                ('number_of_orders', models.IntegerField(default=0)),
                ('number_of_customers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('other_details', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='Uploads/banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Major_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('shop', models.CharField(blank=True, default=1, max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_tech', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_customized', models.BooleanField(default=False)),
                ('is_ugandan', models.BooleanField(default=False)),
                ('is_tagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Net_Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('ordering_code', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=60)),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='None', max_length=100)),
                ('mtn_name', models.CharField(blank=True, default='None', max_length=100)),
                ('mtn', models.CharField(blank=True, default='Empty', max_length=10)),
                ('airtel_name', models.CharField(blank=True, default='None', max_length=100)),
                ('airtel', models.CharField(blank=True, default='Empty', max_length=10)),
                ('Visa', models.CharField(blank=True, default='None', max_length=100)),
                ('visa_number', models.CharField(blank=True, default='Empty', max_length=10)),
                ('vendor_name', models.CharField(default='None', max_length=100)),
                ('dates', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('del_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(default='Categories/arcrid.jpg', upload_to='Uploads/products/')),
                ('image2', models.ImageField(default='Categories/arcrid.jpg', upload_to='Uploads/products/')),
                ('image3', models.ImageField(default='Categories/arcrid.jpg', upload_to='Uploads/products/')),
                ('image4', models.ImageField(default='Categories/arcrid.jpg', upload_to='Uploads/products/')),
                ('shop', models.CharField(default=1, max_length=100)),
                ('shop_name', models.CharField(blank=True, default='Pearlmart', max_length=100)),
                ('dates', models.DateTimeField(default=django.utils.timezone.now)),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.major_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('shop', models.CharField(blank=True, default='Pearl', max_length=100)),
                ('date_sold', models.DateTimeField(default=datetime.datetime.today)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='media/profile')),
                ('phone', models.CharField(blank=True, default='1', max_length=13)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('alternative_Phone', models.CharField(blank=True, default='1', max_length=13)),
                ('shop_name', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('vendor', models.CharField(blank=True, default='None', max_length=100)),
                ('dates', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('shop', models.CharField(blank=True, default=1, max_length=100)),
                ('image', models.ImageField(blank=True, default='Categories/arcrid.jpg', null=True, upload_to='Categories/')),
                ('is_tech', models.BooleanField(default=False)),
                ('is_fashion', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
                ('is_party', models.BooleanField(default=False)),
                ('is_tagged', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.major_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_category'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='posts')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_news', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='Order_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.post')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.IntegerField(default=0)),
                ('bid_price', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
