# Generated by Django 3.2 on 2025-04-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='packaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='product_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='quality_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='under_transportation',
            field=models.BooleanField(default=False),
        ),
    ]
