# Generated by Django 3.2 on 2025-03-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Major_Categories',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Sub_Category',
        ),
    ]
