# Generated by Django 3.2 on 2025-03-29 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_record',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='shop.order'),
        ),
    ]
