# Generated by Django 3.2 on 2025-03-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20250312_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(blank=True, default='Categories/arcrid.jpg', null=True, upload_to='Categories/'),
        ),
    ]
