# Generated by Django 3.2 on 2025-03-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20250314_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='wave_name',
            new_name='Visa',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='wave',
            new_name='visa_number',
        ),
    ]
