# Generated by Django 3.2 on 2025-03-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20250317_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vendor_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='media/profile'),
        ),
    ]
