# Generated by Django 3.2 on 2025-03-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20250317_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/profile'),
        ),
    ]
