# Generated by Django 3.2 on 2025-03-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.major_categories'),
        ),
    ]
