# Generated by Django 3.2 on 2025-03-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20250327_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_accounted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='ordering_code',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='payment_verified',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='status',
        ),
        migrations.AddField(
            model_name='order_record',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order_record',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='dates',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='order_record',
            name='dates',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_record',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order_record',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
